### ISSUE TITLE
Workshop Menu Wrong Link

### ISSUE THREAD

**Issue by ultraJeff** [blues-man/vote-app-guides#13]
Hey there,

Running through this lab and I think there are some broken links in the user workshop modules: The link I have is `https://guides-guides.apps.{CLUSTER_URL}/vote-app-guides/{PATH}`, but I believe it should be `https://guides-guides.apps.{CLUSTER_URL}/inner-outer-guides/{PATH}`

![image](https://github.com/redhat-scholars/inner-outer-guides/assets/2943566/082d6333-b2b4-40b4-a3a6-dd0aa530ba68)

**Comment by blues-man** [comment]
This is fixed with https://github.com/blues-man/vote-app-gitops/commit/3cfc77a61b359fd54bce2845039513b83a1b5e12

Thank you!
