### ISSUE TITLE
patchesJson6902 Deprecated

### ISSUE THREAD

**Issue by ultraJeff** [blues-man/vote-app-guides#14]
Hey all,

Going through the workshop instructions, in Module Three: Production - Pushing to Production you show the [Sync Wave YAML](https://redhat-scholars.github.io/inner-outer-guides/inner-outer-guides/main/m3/production.html?&USERID=user1&SUBDOMAIN=&APIURL=#_reviewing_syncwaves_in_argo_cd) as using `patchesJson6902`, but this has been deprecated for simply `patches` within Kustomize

**Comment by blues-man** [comment]
Good point! I'll updated it asap

**Comment by blues-man** [comment]
Fixed here: https://github.com/blues-man/vote-app-gitops/pull/19

Thanks @cedricclyburn and @ultraJeff !
